### ISSUE TITLE
使用过程中遇到的几个问题(编码 关服 设置)

### ISSUE THREAD

**Issue by katorly** [Zaitonn/Serein#31]
使用版本：[Serein_WPF_v1.3.3_dotnetframework472.zip](https://github.com/Zaitonn/Serein/releases/download/v1.3.3/Serein_WPF_v1.3.3_dotnetframework472.zip)
操作系统：Windows 10 21H1

1. 编码问题如何解决？在设置中我全面使用了UTF-8，但是启动脚本里显示的中文文本全部显示为问号。但如果单纯运行脚本就没这个问题。
![image](https://user-images.githubusercontent.com/70022443/216766865-e0173bc6-cf67-41a7-a295-7f779d1ccb87.png)
（原文是“正在启动服务器...”）
![image](https://user-images.githubusercontent.com/70022443/216766867-ed6758e2-6693-4a4a-b6db-2569ae1101d7.png)
（原文包含“§”）

2. 因为我使用的服务器启动脚本bat是包含了“按任意键可重启”的功能的，因此服务器彻底关闭后serein仍认为进程未结束，一定要我点“结束进程”并确认，我才能关掉serein。如果不考虑在bat文件中删除该功能的话，是否有方法让serein认为服务器进程已结束？
![image](https://user-images.githubusercontent.com/70022443/216766874-15a6bbbc-9456-468f-a6f4-a2b3148f2317.png)
（问号原文是“服务器已关闭”“按任意键重启!”）

3. 主题设置，我打开了跟随系统这个选项，但每次切出这个设置页面再切换回来，这个选项就不是开启状态了，为什么？
![image](https://user-images.githubusercontent.com/70022443/216766882-435f0069-22ab-48ae-a3d4-e2d79d2628ad.png)

**Comment by Zaitonn** [comment]
1. 详见https://serein.cc/#/Tutorial/RunServer?id=%e6%9c%8d%e5%8a%a1%e5%99%a8%e8%be%93%e5%87%ba%e4%b9%b1%e7%a0%81
2. 可能以后会考虑此功能
3. 是bug（我的错T-T
![image](https://user-images.githubusercontent.com/103164490/216767046-160417c3-9ea4-4cde-9417-a5fd035ef3e5.png)

**Comment by Zaitonn** [comment]
java服务器启动好像前面几行都有不可避免的乱码，不清楚是不是java内部的原因

**Comment by katorly** [comment]
> java服务器启动好像前面几行都有不可避免的乱码，不清楚是不是java内部的原因

不清楚，前几行输出中文都是我在bat里用[这几个命令](https://github.com/katorlys/Minecraft-Server-Start/blob/main/Start-press_restart.bat#:~:text=title,Launching...)手动设置的；
最后关服的时候输出中文也出现了乱码

**Comment by Zaitonn** [comment]
> > java服务器启动好像前面几行都有不可避免的乱码，不清楚是不是java内部的原因
> 
> 不清楚，前几行输出中文都是我在bat里用[这几个命令](https://github.com/katorlys/Minecraft-Server-Start/blob/main/Start-press_restart.bat#:~:text=title,Launching...)手动设置的； 最后关服的时候输出中文也出现了乱码

你先试试加那个启动参数能不能管用吧（

**Comment by katorly** [comment]
> > > java服务器启动好像前面几行都有不可避免的乱码，不清楚是不是java内部的原因
> > 
> > 
> > 不清楚，前几行输出中文都是我在bat里用[这几个命令](https://github.com/katorlys/Minecraft-Server-Start/blob/main/Start-press_restart.bat#:~:text=title,Launching...)手动设置的； 最后关服的时候输出中文也出现了乱码
> 
> 你先试试加那个启动参数能不能管用吧（

加了启动参数之后§正常了  
![image](https://user-images.githubusercontent.com/70022443/216795871-06d6d35f-4d6f-469b-983e-d78dc9e878e5.png)  

但中文依然不行
![image](https://user-images.githubusercontent.com/70022443/216795905-eefcf02f-93d8-47ef-bca9-b9996e6a4ebd.png)
![image](https://user-images.githubusercontent.com/70022443/216795917-f7bc1195-73d1-41cf-af09-6697c10ea8d3.png)

**Comment by Zaitonn** [comment]
bat里面加个`chcp 65001`试试

**Comment by katorly** [comment]
> chcp 65001

还是不太行😂  
![image](https://user-images.githubusercontent.com/70022443/216797123-1c0af909-342f-4707-ae38-bc9160e4a4fa.png)
![image](https://user-images.githubusercontent.com/70022443/216797133-cec9a114-8f7c-488b-a374-45b2d9eab9f6.png)

**Comment by Zaitonn** [comment]
要不你来群里问别人看看（我自己没怎么开过Java服🥺
