### ISSUE TITLE
使用单文件部署发行

### ISSUE THREAD

**Issue by StarsDream00** [Zaitonn/Serein#37]
https://learn.microsoft.com/dotnet/core/deploying/single-file

可以同时弃用`Costura.Fody`及`.NET Framework`

**Comment by Zaitonn** [comment]
用.NET Framework主要是为了方便部分用户省得安装运行库（逃
NET6的部分依赖有点bug（https://github.com/Aragas/SystemInfoLibrary/issues/1 ），而且有时候不是很稳定，所以就先把net472留着了

单文件发行我再研究研究，下个版本应该能用上（

**Comment by Zaitonn** [comment]
所以就目前来说还是想把net472保留着（

**Comment by StarsDream00** [comment]
> 用.NET Framework主要是为了方便部分用户省得安装运行库（逃 NET6的部分依赖有点bug（[Aragas/SystemInfoLibrary#1](https://github.com/Aragas/SystemInfoLibrary/issues/1) ），而且有时候不是很稳定，所以就先把net472留着了
> 
> 单文件发行我再研究研究，下个版本应该能用上（

可以同时使用[独立应用程序](https://learn.microsoft.com/zh-cn/dotnet/core/deploying/#publish-self-contained)以生成不需要框架的应用

**Comment by Zaitonn** [comment]
> > 用.NET Framework主要是为了方便部分用户省得安装运行库（逃 NET6的部分依赖有点bug（[Aragas/SystemInfoLibrary#1](https://github.com/Aragas/SystemInfoLibrary/issues/1) ），而且有时候不是很稳定，所以就先把net472留着了
> > 单文件发行我再研究研究，下个版本应该能用上（
> 
> 可以同时使用[独立应用程序](https://learn.microsoft.com/dotnet/core/deploying/#publish-self-contained)以生成不需要框架的应用

太大了点

**Comment by StarsDream00** [comment]
> > > 用.NET Framework主要是为了方便部分用户省得安装运行库（逃 NET6的部分依赖有点bug（[Aragas/SystemInfoLibrary#1](https://github.com/Aragas/SystemInfoLibrary/issues/1) ），而且有时候不是很稳定，所以就先把net472留着了
> 
> > > 单文件发行我再研究研究，下个版本应该能用上（
> 
> > 
> 
> > 可以同时使用[独立应用程序](https://learn.microsoft.com/dotnet/core/deploying/#publish-self-contained)以生成不需要框架的应用
> 
> 
> 
> 太大了点

可以使用[剪裁](https://learn.microsoft.com/dotnet/core/deploying/trimming/trim-self-contained)缩小程序体积

**Comment by Zaitonn** [comment]
> > > > 用.NET Framework主要是为了方便部分用户省得安装运行库（逃 NET6的部分依赖有点bug（[Aragas/SystemInfoLibrary#1](https://github.com/Aragas/SystemInfoLibrary/issues/1) ），而且有时候不是很稳定，所以就先把net472留着了
> > 
> > 
> > > > 单文件发行我再研究研究，下个版本应该能用上（
> > 
> > 
> > > 
> > 
> > 
> > > 可以同时使用[独立应用程序](https://learn.microsoft.com/dotnet/core/deploying/#publish-self-contained)以生成不需要框架的应用
> > 
> > 
> > 太大了点
> 
> 可以使用[剪裁](https://learn.microsoft.com/dotnet/core/deploying/trimming/trim-self-contained)缩小程序体积

wpf和winform不支持这个功能，而且js解释器会用到net的反射，这样搞可能会导致部分功能用不了

**Comment by StarsDream00** [comment]
need to close this as not planned
