### ISSUE TITLE
建议：使用异步或多线程 处理控制台输出 的 正则匹配 等 事件

### ISSUE THREAD

**Issue by lgc2333** [Zaitonn/Serein#47]
emmmm

**Comment by Zaitonn** [comment]
~~（如果你的serein插件没有监听控制台输出的话 可以把`Serein.json`里的Function.JSEventMaxWaitingTime和Function.JSEventCoolingDownTime调小一点（前者可以0，后者100或者更小），理论上可以极大加快输出速度~~

在做了ing
