### ISSUE TITLE
难度无法识别LiteLoaderBDS(2.3.0测试版)

### ISSUE THREAD

**Issue by SPCS233** [Zaitonn/Serein#6]
![Screenshot_20220609_172120_com microsoft rdc androidx](https://user-images.githubusercontent.com/79357769/172813219-57d444e7-fc53-42fd-b924-47431995999d.jpg)

LiteLoaderBDS(2.3.0测试版)（应该不是测试版的问题）

**Comment by SPCS233** [comment]
好像就我在GitHub上反馈

**Comment by Zaitonn** [comment]
你先自己更改一下`settings/Matches.ini`
```ini
# 在此处自定义捕获信息的正则表达式
Version=(\d+\.\d+\.\d+\.\d+)
Difficulty=(PEACEFUL|EASY|NORMAL|HARD[^Y])
LevelName=Level Name: (.+?)$
```

**Comment by Zaitonn** [comment]
> 好像就我在GitHub上反馈

不是啥大问题（可能用的人不那么多
（（你也可以进群反馈：[954829203](https://jq.qq.com/?_wv=1027&k=XNZqPSPv)
