### ISSUE TITLE
[Feature] 当停止服务器命令中没有任何内容时，发送 `Ctrl+C` 信号关服

### ISSUE THREAD

**Issue by lgc2333** [Zaitonn/Serein#62]

**Comment by Zaitonn** [comment]
c# 貌似没提供直接的方法 https://github.com/dotnet/runtime/issues/14628
应该只能调用win32api了 我考虑一下

**Comment by Zaitonn** [comment]
原本强制结束的方法有啥问题么![IE_MA4X}TX)J2JKA(ETO`{J](https://github.com/Zaitonn/Serein/assets/103164490/43ebe61d-a755-4992-bb81-45523236f78a)

**Comment by lgc2333** [comment]
为了应对一些没有stdin的服务端

**Comment by lgc2333** [comment]
我的意思是把强制结束功能搬到普通停止按钮里

**Comment by lgc2333** [comment]
重新说一遍想法，当结束命令里没东西的时候，就发送ctrl+c停止程序，强制停止留着保持原样

**Comment by Zaitonn** [comment]
ojbk了

```
[Serein]启动中
>test
22:13:51 test 
[Serein]当前未设置关服命令，将发送Ctrl+C作为替代
 
[Serein]进程疑似非正常退出（返回：-1073741510）
```

https://github.com/Zaitonn/Serein/actions/runs/5562653207
