### ISSUE TITLE
崩溃反馈 无法找到路径

### ISSUE THREAD

**Issue by LittleChest** [Zaitonn/Serein#64]
### 当前使用的Serein版本

v1.3.5-pre5

### 崩溃日志

2023/7/21 11:07:50  |  v1.3.5-pre5 - wpf  |  NET4.0.30319.42000
编译类型：GITHUB ACTION #414
编译时间：Tue 07/18/2023  9:35:59.86
详细信息：refs/heads/main e9c20786b784aad7044251b838ae71ec21ec9318
System.IO.DirectoryNotFoundException: 未能找到路径“E:\Serein\plugins\permission.json”的一部分。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   在 System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   在 System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   在 Serein.Utils.IO.Data.ReadPermissionGroups() 位置 D:\a\Serein\Serein\Serein\Universal\Utils\IO\Data.cs:行号 420
   在 Serein.Utils.IO.FileSaver.ReadAll() 位置 D:\a\Serein\Serein\Serein\Universal\Utils\IO\Saver.cs:行号 68
   在 Serein.Utils.Runtime.Init() 位置 D:\a\Serein\Serein\Serein\Universal\Utils\Runtime.cs:行号 37
   在 Serein.App..ctor() 位置 D:\a\Serein\Serein\Serein\WPF\App.xaml.cs:行号 24
   在 Serein.App.Main()

### 复现操作

1. 下载Serein
2. 复制到一个方便的位置
3. 打开
4. 崩溃

**Comment by Zaitonn** [comment]
在同目录创个plugins文件夹即可
中午发新版本修复
